export const FETCHING_DATA = "FETCHING_DATA";

export const RECEIVED_USER_INFO = "RECEIVED_USER_INFO";
export const RECEIVED_USER_APPLY = "RECEIVED_USER_APPLY";

export const RECEIVED_COMMON_TYPE = "RECEIVED_COMMON_TYPE";
export const RECEIVED_USER_LIST = "RECEIVED_USER_LIST";
export const RECEIVED_CLASSROOM_LIST = "RECEIVED_CLASSROOM_LIST";
export const RECEIVED_APPLY_LIST = "RECEIVED_APPLY_LIST";
export const RECEIVED_AUDIT_APPLY = "RECEIVED_AUDIT_APPLY";