export const FETCHING_DATA = "FETCHING_DATA";

export const RECEIVED_USER_LIST = "RECEIVED_USER_LIST";
export const RECEIVED_CLASSROOM_LIST = "RECEIVED_CLASSROOM_LIST";
export const RECEIVED_APPLY_LIST = "RECEIVED_APPLY_LIST";
